"""Combine Phase 4-6 outputs into evidence-backed business insights."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import pandas as pd

from src.aspects.aggregation import build_aspect_summary, explode_aspect_mentions
from src.insights.recommendations import generate_recommendations
from src.insights.summaries import generate_executive_summary
from src.insights.trends import TrendAnalysisResult, analyze_trends
from src.insights.utils import (
    InsightFinding,
    InsightsError,
    SENTIMENT_TO_SCORE,
    canonical_sentiment_series,
    minimum_evidence_support,
    representative_ids,
)


@dataclass(frozen=True)
class BusinessInsightsResult:
    """All finalized outputs generated by the Phase 7 insight engine."""

    dataframe: pd.DataFrame
    metrics: dict[str, Any]
    findings: pd.DataFrame
    recommendations: pd.DataFrame
    trends: TrendAnalysisResult
    executive_summary: str


def _sentiment_metrics(dataframe: pd.DataFrame) -> dict[str, Any]:
    labels = canonical_sentiment_series(dataframe["sentiment_label"])
    counts = labels.value_counts().reindex(["Positive", "Neutral", "Negative"], fill_value=0)
    total = int(len(dataframe))
    shares = counts / total if total else counts.astype(float)
    dominant = str(counts.idxmax()) if total else None
    return {
        "dominant_sentiment": dominant,
        "positive_count": int(counts["Positive"]),
        "neutral_count": int(counts["Neutral"]),
        "negative_count": int(counts["Negative"]),
        "positive_share": float(shares["Positive"]) if total else 0.0,
        "neutral_share": float(shares["Neutral"]) if total else 0.0,
        "negative_share": float(shares["Negative"]) if total else 0.0,
    }


def _topic_summary(dataframe: pd.DataFrame) -> pd.DataFrame:
    if "topic_label" not in dataframe.columns:
        return pd.DataFrame()
    work = dataframe.loc[dataframe["topic_label"].notna()].copy()
    if work.empty:
        return pd.DataFrame()
    work["sentiment_label"] = canonical_sentiment_series(work["sentiment_label"])
    work["_sentiment_numeric"] = work["sentiment_label"].map(SENTIMENT_TO_SCORE)
    total = len(dataframe)
    rows: list[dict[str, Any]] = []
    for topic, subset in work.groupby("topic_label", sort=True, observed=True):
        sentiment_counts = subset["sentiment_label"].value_counts()
        rows.append(
            {
                "topic_label": str(topic),
                "review_count": int(len(subset)),
                "share": float(len(subset) / total) if total else 0.0,
                "average_sentiment": float(subset["_sentiment_numeric"].mean()),
                "dominant_sentiment": str(sentiment_counts.idxmax()),
                "negative_share": float(subset["sentiment_label"].eq("Negative").mean()),
                "positive_share": float(subset["sentiment_label"].eq("Positive").mean()),
            }
        )
    return pd.DataFrame(rows).sort_values(
        ["review_count", "topic_label"], ascending=[False, True]
    ).reset_index(drop=True)


def _eligible_aspects(summary: pd.DataFrame, total_reviews: int) -> pd.DataFrame:
    if summary.empty:
        return summary
    threshold = minimum_evidence_support(total_reviews)
    eligible = summary.loc[summary["mention_count"].ge(threshold)].copy()
    return eligible if not eligible.empty else summary.copy()


def _aspect_record(
    row: pd.Series,
    *,
    share_column: str,
    mentions: pd.DataFrame,
) -> dict[str, Any]:
    aspect = str(row["aspect"])
    subset = mentions.loc[mentions["aspect"].astype(str).eq(aspect)] if not mentions.empty else mentions
    ids = representative_ids(subset, limit=3)
    return {
        "aspect": aspect,
        "mention_count": int(row["mention_count"]),
        "positive_share": float(row.get("positive_share", 0.0)),
        "negative_share": float(row.get("negative_share", 0.0)),
        "average_sentiment": (
            None if pd.isna(row.get("average_sentiment")) else float(row.get("average_sentiment"))
        ),
        "representative_review_ids": ids,
        "ranking_metric": float(row[share_column]),
    }


def _select_aspect_extremes(
    summary: pd.DataFrame,
    mentions: pd.DataFrame,
    *,
    total_reviews: int,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    if summary.empty:
        return None, None
    eligible = _eligible_aspects(summary, total_reviews)
    positive = eligible.sort_values(
        ["positive_share", "positive_count", "mention_count", "aspect"],
        ascending=[False, False, False, True],
    ).iloc[0]
    negative = eligible.sort_values(
        ["negative_share", "negative_count", "mention_count", "aspect"],
        ascending=[False, False, False, True],
    ).iloc[0]
    return (
        _aspect_record(positive, share_column="positive_share", mentions=mentions),
        _aspect_record(negative, share_column="negative_share", mentions=mentions),
    )


def _findings(
    dataframe: pd.DataFrame,
    metrics: dict[str, Any],
    *,
    trends: TrendAnalysisResult,
) -> pd.DataFrame:
    records: list[InsightFinding] = []
    sentiment = metrics["sentiment"]
    total = int(metrics["total_reviews"])
    dominant = str(sentiment["dominant_sentiment"])
    dominant_share = float(sentiment[f"{dominant.lower()}_share"])
    dominant_count = int(sentiment[f"{dominant.lower()}_count"])
    records.append(
        InsightFinding(
            category="Overall sentiment",
            title=f"Overall feedback is {dominant.lower()}",
            evidence=f"{dominant_count:,} of {total:,} reviews ({dominant_share:.1%}) are {dominant.lower()}.",
            business_interpretation="Use the overall distribution as context; investigate topics and aspects before deciding what to change.",
            metric_name=f"{dominant} review share",
            metric_value=dominant_share,
            supporting_count=dominant_count,
        )
    )

    topic = metrics.get("most_discussed_topic")
    if topic:
        topic_label = str(topic["topic_label"])
        mask = dataframe["topic_label"].astype(str).eq(topic_label)
        records.append(
            InsightFinding(
                category="Topic",
                title=f'Most discussion centers on "{topic_label}"',
                evidence=(
                    f'{int(topic["review_count"]):,} reviews ({float(topic["share"]):.1%}) '
                    "belong to this topic."
                ),
                business_interpretation="This topic represents the largest share of observed conversation and is a useful starting point for review.",
                metric_name="Topic review share",
                metric_value=float(topic["share"]),
                supporting_count=int(topic["review_count"]),
                affected_item=topic_label,
                representative_review_ids=representative_ids(dataframe, mask=mask, limit=3),
            )
        )

    pain = metrics.get("priority_improvement")
    if pain:
        records.append(
            InsightFinding(
                category="Pain point",
                title=f'Negative feedback is concentrated around "{pain["aspect"]}"',
                evidence=(
                    f'{float(pain["negative_share"]):.1%} of {int(pain["mention_count"]):,} '
                    "observed aspect mentions are negative."
                ),
                business_interpretation="Prioritize manual review of the supporting evidence and investigate possible contributing factors.",
                metric_name="Negative aspect share",
                metric_value=float(pain["negative_share"]),
                supporting_count=int(pain["mention_count"]),
                affected_item=str(pain["aspect"]),
                representative_review_ids=tuple(pain.get("representative_review_ids", ())),
            )
        )

    strength = metrics.get("key_strength")
    if strength:
        records.append(
            InsightFinding(
                category="Strength",
                title=f'Positive feedback is strongest around "{strength["aspect"]}"',
                evidence=(
                    f'{float(strength["positive_share"]):.1%} of {int(strength["mention_count"]):,} '
                    "observed aspect mentions are positive."
                ),
                business_interpretation="Treat this as a product/service strength worth preserving while validating representative reviews.",
                metric_name="Positive aspect share",
                metric_value=float(strength["positive_share"]),
                supporting_count=int(strength["mention_count"]),
                affected_item=str(strength["aspect"]),
                representative_review_ids=tuple(strength.get("representative_review_ids", ())),
            )
        )

    if trends.available and trends.fastest_growing_topic:
        item = trends.fastest_growing_topic
        topic_label = str(item["topic_label"])
        mask = dataframe["topic_label"].astype(str).eq(topic_label)
        records.append(
            InsightFinding(
                category="Trend",
                title=f'"{topic_label}" gained share in the latest period',
                evidence=(
                    f'Topic share changed by {float(item["share_change"]) * 100:.1f} percentage '
                    f'points, with {int(item["supporting_count"]):,} reviews in the latest period.'
                ),
                business_interpretation="Monitor whether this increase persists; observed volume change alone does not establish a cause.",
                metric_name="Topic share change",
                metric_value=float(item["share_change"]),
                supporting_count=int(item["supporting_count"]),
                affected_item=topic_label,
                representative_review_ids=representative_ids(dataframe, mask=mask, limit=3),
            )
        )

    return pd.DataFrame([record.as_dict() for record in records])


def generate_business_insights(
    dataframe: pd.DataFrame,
    *,
    topic_summary: pd.DataFrame | None = None,
    aspect_summary: pd.DataFrame | None = None,
    aspect_mentions: pd.DataFrame | None = None,
) -> BusinessInsightsResult:
    """Generate finalized Phase 7 findings from the Phase 6 enriched DataFrame."""
    required = {
        "review_id",
        "review_text",
        "sentiment_label",
        "topic_id",
        "topic_label",
        "detected_aspects",
        "aspect_sentiment",
    }
    missing = sorted(required.difference(dataframe.columns))
    if missing:
        raise InsightsError(
            "Business insights require Phase 6 enriched results. Missing: " + ", ".join(missing)
        )
    if dataframe.empty:
        raise InsightsError("Business insights require at least one analyzed review.")

    enriched = dataframe.copy(deep=True)
    mentions = (
        aspect_mentions.copy(deep=True)
        if isinstance(aspect_mentions, pd.DataFrame)
        else explode_aspect_mentions(enriched)
    )
    aspects = (
        aspect_summary.copy(deep=True)
        if isinstance(aspect_summary, pd.DataFrame)
        else build_aspect_summary(mentions, total_reviews=len(enriched))
    )
    topics = (
        topic_summary.copy(deep=True)
        if isinstance(topic_summary, pd.DataFrame) and not topic_summary.empty
        else _topic_summary(enriched)
    )

    sentiment = _sentiment_metrics(enriched)
    derived_topics = _topic_summary(enriched)
    most_discussed = None if derived_topics.empty else derived_topics.iloc[0].to_dict()
    key_strength, priority_improvement = _select_aspect_extremes(
        aspects,
        mentions,
        total_reviews=len(enriched),
    )

    metrics: dict[str, Any] = {
        "total_reviews": int(len(enriched)),
        "sentiment": sentiment,
        "most_discussed_topic": most_discussed,
        "key_strength": key_strength,
        "priority_improvement": priority_improvement,
        "topic_count": int(enriched["topic_label"].nunique()),
        "aspect_count": int(mentions["aspect"].nunique()) if not mentions.empty else 0,
        "aspect_coverage": float(
            enriched["detected_aspects"].apply(
                lambda value: isinstance(value, (list, tuple)) and bool(value)
            ).mean()
        ),
    }

    trends = analyze_trends(enriched, aspect_mentions=mentions)
    findings = _findings(enriched, metrics, trends=trends)
    recommendations = generate_recommendations(metrics, trends=trends)
    summary = generate_executive_summary(metrics, trends=trends)

    # Keep supplied topic/aspect summaries consumed for compatibility, while all
    # ranked claims are independently derived from the review-level evidence.
    metrics["topic_summary_rows"] = int(len(topics))
    metrics["aspect_summary_rows"] = int(len(aspects))

    return BusinessInsightsResult(
        dataframe=enriched,
        metrics=metrics,
        findings=findings,
        recommendations=recommendations,
        trends=trends,
        executive_summary=summary,
    )
